import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./login/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          {
            "@import url('https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap');"
          }
        </style>
      </head>
      <body className={`urbanist antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
